site_name: DaSE 课程资料
site_url: https://github.com/tom6m6/DaSE.Courses

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

# 启用搜索
plugins:
  - search:
      lang:
        - zh
        - en

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - admonition
  - footnotes
  - fenced_code
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


# 自动生成导航（按目录结构）
# nav:
#   - 首页: index.md
#   - 课程A:
#       - 第一章: course-a/chapter1.md
#       - 第二章: course-a/chapter2.md
#   - 课程B:
#       - 笔记1: course-b/note1.md
